### ISSUE TITLE
CHANNEL_LAYERS  'asgi_rabbitmq.RabbitmqChannelLayer' specified for default

### ISSUE THREAD

**Issue by sagoyanfisic** [proofit404/asgi_rabbitmq#24]
Traceback (most recent call last):
  File "/home/msalinas/projects/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/msalinas/projects/env/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 38, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "/home/msalinas/projects/env/local/lib/python2.7/site-packages/channels/asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/home/msalinas/projects/env/local/lib/python2.7/site-packages/channels/asgi.py", line 36, in make_backend
    "Cannot import BACKEND %r specified for %s" % (self.configs[name]['BACKEND'], name)
channels.asgi.InvalidChannelLayerError: Cannot import BACKEND 'asgi_rabbitmq.RabbitmqChannelLayer' specified for default

**Comment by proofit404** [comment]
Looks like real problem is hidden by Django checking code. Try to `import asgi_rabbitmq` from python console.

**Comment by sagoyanfisic** [comment]
refleja que no esta instalado _asgi_rabbitmq_  y me aparece que tiene conflicto con pika , como podria corregirlo
 File "/home/msalinas/projects/venv/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2512, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'pika ~=0.11.0', 'at', ' ~=0.11.0')

**Comment by sagoyanfisic** [comment]
use asgi-rabbitmq==0.5.3 and pika==0.9.14 usign perfect!

**Comment by proofit404** [comment]
Why do you need to use old pika release?
