### ISSUE TITLE
AMQPConnectionError 

### ISSUE THREAD

**Issue by sagoyanfisic** [proofit404/asgi_rabbitmq#25]
config: 
CHANNEL_LAYERS = {
   "default": {
       "BACKEND": "asgi_rabbitmq.RabbitmqChannelLayer",
       "ROUTING": "example.routing.channel_routing",
       "CONFIG": {
            'url': 'amqps://guest:guest@rabbitmq:5672/myvhost',
        },
   },
}
 error 
Traceback (most recent call last):
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/channels/management/commands/runserver.py", line 38, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/channels/asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/channels/asgi.py", line 44, in make_backend
    asgi_layer = backend_class(**self.configs[name].get("CONFIG", {}))
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/asgi_rabbitmq/core.py", line 786, in __init__
    self.get_capacity, crypter)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/asgi_rabbitmq/core.py", line 730, in __init__
    get_capacity, crypter)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/asgi_rabbitmq/core.py", line 621, in __init__
    lock=self.lock,
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/asgi_rabbitmq/core.py", line 565, in __init__
    super(LayerConnection, self).__init__(*args, **kwargs)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/pika/adapters/select_connection.py", line 76, in __init__
    stop_ioloop_on_close)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/pika/adapters/base_connection.py", line 80, in __init__
    on_close_callback)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/pika/connection.py", line 613, in __init__
    self.connect()
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/pika/connection.py", line 756, in connect
    error)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/home/msalinas/projects/envname/lib/python3.4/site-packages/pika/connection.py", line 1265, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: Connection to 208.73.211.70:5672 failed: [Errno 111] Connection refused

**Comment by proofit404** [comment]
Is rabbitmq server running properly? Is channels config set properly?
