### ISSUE TITLE
Channels 2.0 support?

### ISSUE THREAD

**Issue by LiteWait** [proofit404/asgi_rabbitmq#28]
I was wondering is asgi_rabbitmq has been tested with Channels 2.0 yet. If not is there a roadmap of the required changes.  Happy to QA it, really don't want to head to production using Redis, way too many moving parts.

**Comment by muchwakande** [comment]
I tried using it. Got this error

**
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fb7e526bbf8>
Traceback (most recent call last):
  File "~/.envs/ProjectEnv/lib/python3.5/site-packages/channels/layers.py", line 53, in _make_backend
    backend_class = import_string(self.configs[name]["BACKEND"])
  File "~/.envs/ProjectEnv/lib/python3.5/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "~/.envs/ProjectEnv/lib/python3.5/site-packages/asgi_rabbitmq/__init__.py", line 1, in <module>
    from .core import RabbitmqChannelLayer
  File "~/.envs/ProjectEnv/lib/python3.5/site-packages/asgi_rabbitmq/core.py", line 8, in <module>
    from asgiref.base_layer import BaseChannelLayer
ImportError: No module named 'asgiref.base_layer'

**Comment by proofit404** [comment]
Hi all,

I did not put any effort yet to implement 2.0 support.

Regards, Artem.

**Comment by cho-is** [comment]
I am facing the same issue :(

**Comment by eavictor** [comment]
Channels 2.0 has removed base_layer, so the exception is expected.
I really love the stability and scalability of RabbitMQ so I decide to stick with asgi_rabbitmq :)

Just specify channels version ```channels==1.1.8``` or ```channels~=1.1.8``` in requirements.txt


If every "message" on your service is important and cannot be dropped by any accident, please stick with proofit404, I believe he will have some free time to look into channels 2.0 in the near future.

**Comment by proofit404** [comment]
Thanks for your patience!

**Comment by eavictor** [comment]
I just took a brief look into Channels 2.0 code and compare to 1.0

The change is way too huge and only support from Python 3.5~
Maybe it's a good idea to start new repository rather than modify current one.

**Comment by 0x55AAh** [comment]
Is there any progress?

**Comment by proofit404** [comment]
No. I do not use Channels in any of my current projects. So I do not work on asgi_rabbitmq due to lack of time.
