### ISSUE TITLE
Runworker process hangs after AMQPConnectionError exception

### ISSUE THREAD

**Issue by nmgeek** [proofit404/asgi_rabbitmq#29]
My rabbitmq server is running on an AWS instance.  I have one remote _runworker_ client, connecting over the internet. After some time there may be some brief interruption in internet service and the asgi thread raises  _AMQPConnectionError_.  I assume this kills its thread but the main _runworker_ process does not detect that the connection was lost and appears to hang.  The client shows as disconnected from the rabbitmq server.

Without the ability to detect and reconnect after an intermittent internet outage I cannot move my software to production.  I'm stuck.

Heartbeats are generated by the _runworker_ client at a 10 second interval.

Occasionally a _ConnectionClosed_ exception is raised in the _runworker_ process and it exits.  But other
times it hangs and never exits.

My configuration:
```
rabbitmq-server: 3.6.15
asgi-rabbitmq==0.5.3
asgiref==1.1.2
channels==1.1.8
pika==0.10.0
```
The thread death traceback:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/asgi_rabbitmq/core.py", line 735, in run
    self.connection.run()
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/asgi_rabbitmq/core.py", line 627, in run
    self.connection.ioloop.start()
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 355, in start
    self.process_timeouts()
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 283, in process_timeouts
    timer['callback']()
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/pika/connection.py", line 756, in connect
    error)
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/sigma/apps/sigmalabs-daqadaptor/local/lib/python2.7/site-packages/pika/connection.py", line 1265, in _on_connection_error
    self.params.connection_attempts)
AMQPConnectionError: Connection to X.X.X.X:5672 failed: timeout
```

**Comment by HIJADI** [comment]
The connection parameters are set like:  heartbeat_interval=10&connection_attempts=10
http://pika.readthedocs.io/en/latest/modules/parameters.html#urlparameters
Perhaps could also increase the low level socket_timeout?

**Comment by nmgeek** [comment]
I walked through the details of the process that leads to this un-monitored thread death and discovered that it is happening in the process of connecting during runworker startup.  From what I see there may be a solution that involves registering an `on_open_error_callback` when `pika.adapters.select_connection.SelectConnection` is instantiated.
