### ISSUE TITLE
AttributeError: 'ConnectionThread' object has no attribute '_started'

### ISSUE THREAD

**Issue by caronc** [proofit404/asgi_rabbitmq#6]
I get the following error when I use this asgi plugin (with RabbitMQ):
```bash
Starting Channels development server at http://192.168.0.9:8080/
Channel layer default (asgi_rabbitmq.core.RabbitmqChannelLayer)
Quit the server with CONTROL-C.
2017-06-05 23:55:05,799 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-06-05 23:55:05,801 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-06-05 23:55:05,803 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-06-05 23:55:05,804 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-06-05 23:55:05,806 - INFO - server - HTTP/2 support enabled
2017-06-05 23:55:05,808 - INFO - server - Using busy-loop synchronous mode on channel layer
2017-06-05 23:55:05,809 - INFO - server - Listening on endpoint tcp:port=8080:interface=127.0.0.1
2017-06-05 23:55:05,816 - ERROR - server - Error trying to receive messages: 'ConnectionThread' object has no attribute '_started'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 166, in run
    worker.run()
  File "/usr/lib/python2.7/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/usr/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/usr/lib/python2.7/site-packages/asgi_rabbitmq/core.py", line 659, in receive
    future = self.thread.schedule(RECEIVE, channels, block)
  File "/usr/lib/python2.7/site-packages/asgi_rabbitmq/core.py", line 636, in thread
    if not self._thread._started.is_set():
AttributeError: 'ConnectionThread' object has no attribute '_started'

Exception in thread Thread-3:
...<same error>...
AttributeError: 'ConnectionThread' object has no attribute '_started'
...
...
<this error continues for all threads>
```

I running CentOS 7.x with the following packages:
* Python v2.7.5
* asgiref v1.1.2
* asgi_rabbitmq v0.5
* Rabbitmq v3.6.5
* channels v1.1.3
* Django v1.10.7

Any advice?

**Comment by proofit404** [comment]
Fixed in the `0.5.1`. Already on PyPI. Thanks for the report.
